### ISSUE TITLE
Planned providers

### ISSUE THREAD

**Issue by jmthackett** [OpenNebula/addon-host-provision#1]
Do you have a list of other providers you're planning to support? 

I'd like to suggest Scaleway if you're taking suggestions: they do 'baremetal' servers through an API and they're very cheap. There's already an inventory source and an ansible module in existence (https://docs.ansible.com/ansible/latest/plugins/inventory/scaleway.html and eg https://docs.ansible.com/ansible/latest/modules/scaleway_compute_module.html among others) to work from.

**Comment by vholer** [comment]
Hello John,

for now, there are no plans to support any other providers than EC2 and Packet. We now focus on improving the tool itself and working on providing the best experience of the deployed KVM clouds on the current remote providers. Fortunately, we have an extensive documentation about how to write new provision drivers (https://docs.opennebula.org/addon/host-provision/integration/infrastructure_integration/devel-pm.html), so if the community helps us with the new drivers, we can include them.

To support Scaleway at some point is very good idea, I have opened a tracking issue in the main ONE repository (https://github.com/OpenNebula/one/issues/2617). If interested, please subscribe to the ticket there.

Thank you for your feedback!
Vlastimil Holer
